version: 2

updates:
  - package-ecosystem: cargo
    directory: /packages/rust
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      rust-minor:
        update-types: [minor, patch]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns: ["*"]
