/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1'

/** Every device the build knows. Reads no hardware. */
export declare class Catalog {
  /** The catalog compiled into this build. */
  static embedded(): Catalog
  /** Every SKU that resolves, verified aliases included. */
  skus(): Array<string>
  /** Whether a SKU resolves. */
  has(sku: string): boolean
  /**
   * One device file, with every `include:` and every override applied.
   *
   * Throws with the code `unknown_sku` when nothing declares it.
   */
  device(sku: string): any
  /** How many device files the build carries. */
  get size(): number
  toString(): string
}

/**
 * The configuration in force. Every field is read-only: the SDK reads the
 * configuration once, at startup.
 */
export declare class Config {
  /** The default configuration: `lan` alone, and no device entry. */
  constructor()
  /**
   * Read `$XDG_CONFIG_HOME/govee-toolkit/config.yaml`.
   *
   * A missing file is the default configuration, not an error. A file that
   * does not parse throws with the code `config`.
   */
  static load(): Config
  /** Read the configuration from one path. */
  static loadFrom(path: string): Config
  /** The modes enabled for a device with no entry of its own. */
  get defaultModes(): Array<string>
  /** The identity of every device the file names. */
  get devices(): Array<string>
  /** The rate a stream sends at when the device file measured none. */
  get streamFallbackHz(): number
  /**
   * The whole configuration, as the core serializes it. It carries no
   * credential: a key comes from the environment, never from the file.
   */
  toJSON(): any
  toString(): string
}

/** A device the SDK knows about. */
export declare class Device {
  /** The MAC it reports, uppercased. */
  get id(): string
  /** The SKU it is encoded under. */
  get sku(): string
  /** The name the configuration gives it, if any. */
  get name(): string | null
  /** The enabled modes, in preference order. */
  get modes(): Array<string>
  /**
   * Its health per enabled mode. A mode is absent when no transport has
   * heard from it.
   */
  get health(): Record<string, Health>
  toString(): string
}

/**
 * A handle on one identity. It holds no state of its own: every answer comes
 * from the SDK it was made by.
 */
export declare class DeviceHandle {
  /** The MAC the device reports, uppercased. */
  get id(): string
  /** The modes enabled for it, in preference order. */
  get modes(): Array<string>
  /**
   * Its health in one mode. `null` when the transport that serves that
   * mode has never heard from it.
   */
  health(mode: string): Health | null
  /**
   * The mode a command sent now would go over. Read from recorded state,
   * so the answer can change before the next call.
   */
  servingMode(): string
  /** What `devices/<SKU>.yaml` declares for it. Reads no hardware. */
  spec(): any
  /**
   * What `devices/<SKU>.yaml` declares, as the record `govee describe`
   * prints: the modes in one place, the commands under the mode that
   * carries them, and each argument's type, role and bound.
   */
  describe(): any
  /** The last status heard, without asking for a new one. */
  lastStatus(): DeviceStatus | null
  /**
   * Watch its status as answers arrive, over the mode that would serve a
   * command now. `null` when no enabled mode can, or when that transport
   * has heard nothing.
   */
  watchStatus(): StatusStream | null
  /**
   * Scan for the device if no mode knows it yet, then answer the mode a
   * command would go over.
   */
  ensureKnown(): Promise<string>
  /**
   * Send a command, named as the device file names it.
   *
   * The arguments are the ones the entry declares, and each value is read
   * under the type the entry declares for it. A value outside the declared
   * range throws with the code the codec gives it, and nothing is sent.
   */
  send(command: string, args?: Record<string, boolean | number | string | Uint8Array | Array<number> | Array<[number, number, number]>>): Promise<Served>
  /**
   * Run a command's exchanges and return what its `reply:` layouts
   * captured.
   */
  read(command: string, args?: Record<string, boolean | number | string | Uint8Array | Array<number> | Array<[number, number, number]>>): Promise<Reply>
  /** Ask the device for its state and wait for the answer. */
  status(): Promise<DeviceStatus>
  /** Turn the device on or off. */
  power(on: boolean): Promise<Served>
  /**
   * Set the level, in the unit the device file declares. A level outside
   * that range is an error, never a clamp.
   */
  brightness(level: number): Promise<Served>
  /** Set one color, as three channels. */
  color(rgb: [number, number, number]): Promise<Served>
  /** Set the white temperature, in kelvin. It ends color mode. */
  colorTemp(kelvin: number): Promise<Served>
  /**
   * Play an effect the device renders from its own microphone.
   *
   * The identifiers are the mode's own: one the entry accepts is not one
   * the device renders. `color` imposes a color, and `null` leaves the
   * colors to the firmware.
   *
   * `null` takes the core's default for `sensitivity` and for `soft`.
   */
  music(effect: number, sensitivity?: number | undefined | null, soft?: boolean | undefined | null, color?: [number, number, number]): Promise<Served>
  /**
   * Paint the segments once.
   *
   * One color fills every zone, and an array states them all. A zone list
   * takes one color. `resolution` takes `"app"` when it is `null`.
   */
  segment(colors: [number, number, number] | Array<[number, number, number]>, zones?: Array<number> | undefined | null, resolution?: number | 'app' | 'native', gradient?: boolean | undefined | null): Promise<Served>
  /**
   * Ask the firmware to interpolate between zones, and to wrap from the
   * last zone back to the first.
   */
  gradient(on: boolean): Promise<Served>
  /**
   * Put the device on a Wi-Fi network over `ble`.
   *
   * The device must be in Bluetooth range and closed in the phone
   * controller. The password travels in plaintext: anything in Bluetooth
   * range during the transfer reads it. The network must be 2.4 GHz.
   *
   * Answers `"accepted"` where the device acknowledged the transfer, and
   * `"sent"` where its device file declares no acknowledgement.
   */
  provisionWifi(network: string, password: string, utcOffsetHours?: number | undefined | null, utcOffsetMinutes?: number | undefined | null): Promise<string>
  /**
   * Open the raw segment channel and paint it frame by frame.
   *
   * Power the device on first: arming a dark strip paints nothing. The
   * channel holds the colors only while it is armed, and the device goes
   * back to the color it showed before once the stream closes.
   *
   * `resolution` takes `"app"` when it is `null`, and `rate` takes
   * `"measured"`.
   */
  openStream(resolution?: number | 'app' | 'native', rate?: number | 'measured', gradient?: boolean | undefined | null): Promise<SegmentStream>
  toString(): string
}

/** What a device reported about itself. No firmware fills every field. */
export declare class DeviceStatus {
  /** Which device answered. */
  get id(): string
  /** Whether it is on. */
  get on(): boolean | null
  /**
   * The level it reports. A percentage on every unit seen so far, and not
   * normalized here.
   */
  get brightness(): number | null
  /** The color, as three channels. Reset to `[0, 0, 0]` in white mode. */
  get color(): [number, number, number] | null
  /** The white temperature. `0` means the device is in color mode. */
  get colorTempKelvin(): number | null
  /** The whole reply, with every field the SDK does not model. */
  get raw(): any
  /** Whether the device is in white mode. Mutually exclusive with color. */
  get isWhite(): boolean
  toString(): string
}

/**
 * The events of one SDK. Iterate it with `for await`.
 *
 * Every event is a plain object, and `event` says which one it is. The
 * records are the core's own, so `govee watch --json` prints the same ones.
 * A subscription that falls behind reports `{ event: "lagged", missed: n }`
 * rather than hide the gap.
 */
export declare class EventStream {
  /** The next event, or `null` once the SDK that reported them is gone. */
  next(): Promise<any | undefined | null>
}

/**
 * The SDK. Start one and keep it: it holds the catalog, the configuration
 * and one transport per mode.
 */
export declare class Govee {
  /**
   * Start the SDK. Without a configuration, it reads the file. Without a
   * catalog, it reads the one the package carries.
   */
  static start(config?: Config | undefined | null, catalog?: Catalog | undefined | null): Promise<Govee>
  /**
   * Run a discovery scan on every mode and return what answered.
   *
   * The scans run at the same time, so the call takes the longest window
   * and not their sum. Nothing on the send path calls this.
   */
  scan(): Promise<Array<Device>>
  /**
   * Run a discovery scan on the modes named.
   *
   * A mode this build carries no transport for contributes nothing and is
   * not an error.
   */
  scanOn(modes: Array<string>): Promise<Array<Device>>
  /**
   * Every device known, across every mode. One reachable over two modes
   * appears once.
   */
  devices(): Array<Device>
  /**
   * The modes this build carries a transport for. Not a preference order:
   * that is each device's own configuration.
   */
  modes(): Array<string>
  /** Everything wrong with the configuration, as one sentence each. */
  problems(): Array<string>
  /** The configuration in force. */
  get config(): Config
  /** The device catalog in force. */
  get catalog(): Catalog
  /** A handle for one device, by the MAC it reports. */
  device(id: string): DeviceHandle
  /** Subscribe to what the SDK reports. Iterate it with `for await`. */
  events(): EventStream
  /**
   * Release what every transport holds. Call it before the program ends,
   * or `ble` loses the last frame it wrote.
   */
  close(): Promise<undefined>
  toString(): string
}

/** A device's health in one mode. */
export declare class Health {
  /** `"ok"`, `"degraded"` or `"down"`. */
  get state(): string
  /** Consecutive unanswered verifications. */
  get failures(): number
  /** Whether a command would be sent right now. */
  get available(): boolean
  toString(): string
}

/** What one command's `reply:` layouts captured. */
export declare class Reply {
  /** Which device answered. */
  get id(): string
  /**
   * Every field the exchanges captured, by the name the device file gives
   * it.
   */
  get fields(): any
  toString(): string
}

/**
 * An open segment channel. The writers never block: each one replaces what
 * the next frame carries.
 *
 * Close it, or leave it with `await using`. A stream that is collected
 * disarms the channel as well, and reports no failure.
 */
export declare class SegmentStream {
  /**
   * How many zones the frames carry. The firmware reads the count off the
   * frame, so it never changes while the stream is open.
   */
  get zones(): number
  /** How fast frames go out, in hertz. */
  get rateHz(): number
  /** How many frames reached the wire. */
  get framesSent(): number
  /** How many frames a later write replaced before they left. */
  get framesSuperseded(): number
  /**
   * What the emitting task failed with, if it failed. The stream stops
   * sending, and the writers keep answering.
   */
  get error(): string | null
  /** State every zone. The count must be the stream's own. */
  setAll(colors: Array<[number, number, number]>): void
  /** State one zone, by its zero-based index. */
  setZone(index: number, color: [number, number, number]): void
  /** Put one color in every zone. */
  fill(color: [number, number, number]): void
  /** Put black in every zone. The channel stays armed. */
  clear(): void
  /** What the next frame carries. */
  buffer(): Array<[number, number, number]>
  /** Disarm the channel and wait for the last frame to leave. */
  close(): Promise<undefined>
  toString(): string
}

/** A command that was served. */
export declare class Served {
  /** The device it went to. */
  get id(): string
  /** The mode that served it. */
  get mode(): string
  /** The device file entry that was sent. */
  get command(): string
  /** The name the wire carries, where it carries one. */
  get cmd(): string
  toString(): string
}

/**
 * One device's status, as answers arrive. Iterate it with `for await`.
 *
 * It requests nothing: it reports the answers a status request or a
 * verification already brought back.
 */
export declare class StatusStream {
  /**
   * The next status, or `null` once the transport that heard this device
   * is gone.
   */
  next(): Promise<DeviceStatus | undefined | null>
}

/** The version of the core this binding was built from. */
export declare const CORE_VERSION: string

/**
 * Every mode name the core knows. A build carries a transport for those its
 * features name — `Govee.modes()` answers which.
 */
export declare function modes(): Array<string>

/** The version of this binding. */
export declare const VERSION: string
